//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub board_id: Uuid,
    pub root_post_id: Uuid,
    pub parent_post_id: Option<Uuid>,
    pub author_tripcode: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub reply_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub last_bumped_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Boards,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentPostId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
